# -*- coding: utf-8 -*-
"""Build az.json / ru.json by translating every English leaf string."""
from pathlib import Path
import json, re, copy

ROOT = Path(__file__).resolve().parent
src = (ROOT / "build_i18n.py").read_text(encoding="utf-8")
m = re.search(r"^en = \{", src, re.M)
marker = src.find("\nimport copy", m.start())
ns = {}
exec(src[m.start():marker], ns)
en = ns["en"]

# EN -> AZ / RU for every unique leaf currently in en
AZ = {
"Booking": "Bron", "Destinations": "İstiqamətlər", "Experience": "Təcrübə", "About": "Haqqımızda",
"My Trips": "Səyahətlərim", "Login": "Giriş", "Logout": "Çıxış", "Notifications": "Bildirişlər",
"Profile": "Profil", "Open menu": "Menyunu aç", "Close menu": "Menyunu bağla", "Search": "Axtarış",
"Primary": "Əsas", "AEROVA Home": "AEROVA Ana səhifə",
"Fly beyond expectations.": "Gözləntilərinizin fövqünə uçun.", "Quick Links": "Sürətli keçidlər",
"Home": "Ana səhifə", "Flights": "Uçuşlar", "Support": "Dəstək", "Help Center": "Kömək mərkəzi",
"Contact Us": "Əlaqə", "Travel Information": "Səyahət məlumatı", "FAQs": "Suallar",
"Follow Us": "Bizi izləyin", "© 2026 AEROVA. All rights reserved.": "© 2026 AEROVA. Bütün hüquqlar qorunur.",
"Privacy Policy": "Məxfilik siyasəti", "Terms & Conditions": "Şərtlər və qaydalar",
"Manage Booking": "Bronu idarə et",
"Continue": "Davam et", "Back": "Geri", "Next": "Növbəti", "Cancel": "Ləğv et", "Save": "Yadda saxla",
"Clear": "Təmizlə", "Close": "Bağla", "From": "Haradan", "To": "Haraya", "Departure": "Gediş",
"Return": "Dönüş", "Passengers": "Sərnişinlər", "Passenger": "Sərnişin", "Cabin Class": "Salon sinfi",
"Economy": "Ekonom", "Comfort": "Komfort", "Business": "Biznes", "Non-stop": "Birbaşa",
"1 Stop": "1 dayanacaq", "Price": "Qiymət", "Duration": "Müddət", "Stops": "Dayanacaqlar",
"Date": "Tarix", "Flight": "Uçuş", "Status": "Status", "Total": "Cəmi", "Details": "Ətraflı",
"Select": "Seç", "Selected": "Seçilib", "Available": "Mövcud", "Unavailable": "Mövcud deyil",
"Required": "Məcburi", "Optional": "İstəyə bağlı", "Adult": "Böyük", "Child": "Uşaq",
"Infant": "Körpə", "Yes": "Bəli", "No": "Xeyr", "Loading…": "Yüklənir…", "Edit": "Redaktə",
"Remove": "Sil", "Add": "Əlavə et", "Apply": "Tətbiq et", "Confirm": "Təsdiq et",
"Download": "Yüklə", "View": "Bax", "None": "Yoxdur", "None selected": "Seçilməyib",
"per passenger": "hər sərnişinə", "Included": "Daxildir", "Free": "Pulsuz", "Language": "Dil",
"Luxury Travel Experience": "Lüks Səyahət Təcrübəsi", "Your Journey": "Səyahətiniz",
"Starts Here": "Buradan Başlayır",
"Discover new destinations, create unforgettable memories and fly beyond expectations.": "Yeni istiqamətlər kəşf edin, unudulmaz xatirələr yaradın və gözləntilərinizin fövqünə uçun.",
"Book Now": "İndi bron et", "Where Would You Like To Fly?": "Haraya uçmaq istəyirsiniz?",
"Try: Baku to Dubai next Friday, 2 passengers, business": "Məsələn: Bakıdan Dubaya gələn cümə, 2 sərnişin, biznes",
"Search Flights": "Uçuş axtar", "Speak or type your trip in one sentence.": "Səyahətinizi bir cümlə ilə deyin və ya yazın.",
"Featured Destinations": "Seçilmiş istiqamətlər", "Where Will You Go Next?": "Növbəti dayanacağınız haradır?",
"Explore unforgettable destinations with AEROVA.": "AEROVA ilə unudulmaz istiqamətləri kəşf edin.",
"Explore": "Kəşf et", "Why AEROVA": "Niyə AEROVA", "Travel, Elevated": "Səyahət, yüksək səviyyədə",
"Every detail designed for calm, clarity, and comfort.": "Hər detal sakitlik, aydınlıq və rahatlıq üçün düşünülüb.",
"Refined Comfort": "Zərif rahatlıq", "Thoughtfully designed cabins for every journey.": "Hər səyahət üçün düşünülmüş salonlar.",
"Signature Destinations": "İmza istiqamətlər",
"Curated routes connecting the world's most compelling cities.": "Dünyanın ən cəlbedici şəhərlərini birləşdirən seçilmiş marşrutlar.",
"Premium Experience": "Premium təcrübə",
"Discover a refined travel experience designed around you.": "Sizin ətrafınızda dizayn edilmiş zərif səyahət təcrübəsini kəşf edin.",
"The Aerova Experience": "Aerova Təcrübəsi", "Travel in a Class of Your Own": "Öz sinfinizdə səyahət edin",
"From refined comfort to elevated service, discover the way you want to travel with AEROVA.": "Zərif rahatlıqdan yüksək xidmətə qədər AEROVA ilə səyahət tərzinizi kəşf edin.",
"Economy Class": "Ekonom sinif",
"Thoughtful comfort, entertainment and everything you need for a smooth journey.": "Düşünülmüş rahatlıq, əyləncə və rahat səyahət üçün lazım olan hər şey.",
"Explore Economy": "Ekonomu kəşf et",
"Extra space, thoughtful amenities and a more relaxed way to travel.": "Əlavə yer, düşünülmüş rahatlıq və daha sakit səyahət.",
"Discover Comfort": "Komfortu kəşf et", "Business Class": "Biznes sinif",
"Enjoy spacious seating, refined dining and a more comfortable journey.": "Geniş oturacaqlar, zərif yeməklər və daha rahat səyahət.",
"Explore Business": "Biznesi kəşf et", "Stay Connected": "Əlaqədə qalın",
"Travel Inspiration, Delivered": "Səyahət ilhamı, birbaşa sizə",
"Subscribe to receive AEROVA travel updates, destination inspiration and exclusive offers.": "AEROVA yenilikləri, istiqamət ilhamı və xüsusi təkliflər üçün abunə olun.",
"Email address": "E-poçt ünvanı", "Enter your email address": "E-poçt ünvanınızı daxil edin",
"Subscribe": "Abunə ol", "Thank you for subscribing.": "Abunə olduğunuz üçün təşəkkürlər.",
"Please enter a valid email address.": "Düzgün e-poçt ünvanı daxil edin.",
"Aircraft in flight above the clouds": "Buludların üzərində uçan təyyarə",
"Book Your Flight": "Uçuşunuzu bron edin", "Find Your AEROVA Flight": "AEROVA uçuşunuzu tapın",
"Search, compare and book your perfect journey.": "Axtarın, müqayisə edin və mükəmməl səyahətinizi bron edin.",
"Round Trip": "Gediş-dönüş", "One Way": "Biristiqamətli", "Multi City": "Çoxşəhərli",
"City or airport": "Şəhər və ya hava limanı", "Departure Date": "Gediş tarixi",
"Return Date": "Dönüş tarixi", "Trip type": "Səyahət növü", "Flight {n}": "Uçuş {n}",
"Add Flight": "Uçuş əlavə et", "Adults": "Böyüklər", "Children": "Uşaqlar", "Infants": "Körpələr",
"Your Search": "Axtarışınız", "Select Dates": "Tarixləri seçin",
"Select departure date": "Gediş tarixini seçin", "Select return date": "Dönüş tarixini seçin",
"Modify search": "Axtarışı dəyiş", "Voice input for departure": "Gediş üçün səsli daxiletmə",
"Voice input for destination": "Təyinat üçün səsli daxiletmə",
"Swap departure and destination": "Gediş və təyinatı dəyiş", "Flight booking": "Uçuş bronu",
"Please enter a departure city.": "Gediş şəhərini daxil edin.",
"Please enter a destination.": "Təyinat şəhərini daxil edin.",
"Departure and destination must be different.": "Gediş və təyinat fərqli olmalıdır.",
"Please select a departure date.": "Gediş tarixini seçin.",
"Please select a return date.": "Dönüş tarixini seçin.",
"Return date must be after departure.": "Dönüş tarixi gedişdən sonra olmalıdır.",
"Please select at least one passenger.": "Ən azı bir sərnişin seçin.",
"Available Flights": "Mövcud uçuşlar",
"Available flights in the next 30 days": "Növbəti 30 gün ərzində mövcud uçuşlar",
"← Modify search": "← Axtarışı dəyiş", "Filters & Sort": "Filtrlər və çeşidləmə",
"Clear Filters": "Filtrləri təmizlə", "Sort By": "Çeşidlə", "Recommended": "Tövsiyə olunan",
"Cheapest": "Ən ucuz", "Fastest": "Ən sürətli", "Earliest Departure": "Ən erkən gediş",
"Lowest to Highest": "Artan qiymət", "Highest to Lowest": "Azalan qiymət",
"Shortest": "Ən qısa", "Longest": "Ən uzun", "1 flight found": "1 uçuş tapıldı",
"{count} flights found": "{count} uçuş tapıldı",
"0 flights match your filters": "Filtrlərə uyğun uçuş yoxdur", "Select Flight": "Uçuşu seç",
"View Details": "Ətraflı bax", "Departs": "Gediş", "Arrives": "Gəliş",
"Flight filters and sorting": "Uçuş filtrləri və çeşidləmə", "Flight options": "Uçuş seçimləri",
"No flights found": "Uçuş tapılmadı",
"Try adjusting your filters or modifying your search.": "Filtrləri dəyişin və ya axtarışı yeniləyin.",
"Flight Details": "Uçuş detalları", "Flight Overview": "Uçuşa baxış", "Schedule": "Cədvəl",
"Aircraft": "Təyyarə", "Cabin Options": "Salon seçimləri",
"Continue to Seat Selection": "Oturacaq seçiminə keç", "Back to Results": "Nəticələrə qayıt",
"Amenities": "İmkanlar", "Baggage": "Baqaj", "From {price}": "{price}-dən",
"Select Your Seats": "Oturacaqlarınızı seçin", "Choose seats for each passenger.": "Hər sərnişin üçün oturacaq seçin.",
"Occupied": "Məşğul", "Extra legroom": "Əlavə ayaq yeri", "Selection Summary": "Seçim xülasəsi",
"Selected seats": "Seçilmiş oturacaqlar", "No seat selected": "Oturacaq seçilməyib",
"Select a seat for {name}": "{name} üçün oturacaq seçin", "Passenger {n}": "Sərnişin {n}",
"Please select a seat for every passenger.": "Hər sərnişin üçün oturacaq seçin.",
"This seat is unavailable.": "Bu oturacaq mövcud deyil.", "Seat map": "Oturacaq xəritəsi",
"Passenger Details": "Sərnişin məlumatları",
"Enter traveler information exactly as it appears on travel documents.": "Məlumatları səyahət sənədlərindəki kimi daxil edin.",
"Booking Contact": "Bron əlaqəsi", "Email": "E-poçt", "Phone": "Telefon",
"First Name": "Ad", "Last Name": "Soyad", "Title": "Müraciət", "Date of Birth": "Doğum tarixi",
"Nationality": "Vətəndaşlıq", "Passport Number": "Pasport nömrəsi",
"Passport Expiry": "Pasportun bitmə tarixi", "Booking Summary": "Bron xülasəsi",
"Continue to Payment": "Ödənişə keç", "Save passenger": "Sərnişini yadda saxla",
"This field is required": "Bu sahə mütləqdir", "Enter a valid email address": "Düzgün e-poçt daxil edin",
"Enter a valid phone number": "Düzgün telefon daxil edin",
"Baggage Selection": "Baqaj seçimi", "Add checked baggage for your journey.": "Səyahətiniz üçün əlavə baqaj seçin.",
"Cabin bag included": "Əl baqajı daxildir", "Continue without extra baggage": "Əlavə baqajsız davam et",
"Baggage total": "Baqaj cəmi", "Baggage for {name}": "{name} üçün baqaj",
"No extra baggage": "Əlavə baqaj yoxdur", "23 kg checked bag": "23 kq yoxlanılan baqaj",
"32 kg checked bag": "32 kq yoxlanılan baqaj", "2 × 23 kg checked bags": "2 × 23 kq yoxlanılan baqaj",
"Meal Selection": "Yemək seçimi", "Choose meals for your flight.": "Uçuşunuz üçün yemək seçin.",
"Continue without meals": "Yeməksiz davam et", "Meals total": "Yemək cəmi",
"Standard meal": "Standart yemək", "Vegetarian": "Vegetarian", "Vegan": "Vegan", "Halal": "Halal",
"Children's meal": "Uşaq yeməyi", "No meal selected": "Yemək seçilməyib",
"Meal for {name}": "{name} üçün yemək",
"Extra Services": "Əlavə xidmətlər",
"Enhance your journey with optional extras.": "İstəyə bağlı xidmətlərlə səyahətinizi zənginləşdirin.",
"Continue without extras": "Əlavəsiz davam et", "Extras total": "Əlavələr cəmi",
"Airport Lounge Access": "Hava limanı zalı",
"Relax before departure in a premium lounge.": "Gedişdən əvvəl premium zalda dincəlin.",
"Priority Boarding": "Prioritet miniş", "Board early and settle in with ease.": "Daha tez minin və rahat yerləşin.",
"Inflight Wi‑Fi": "Uçuşdaxili Wi‑Fi", "Stay connected throughout your flight.": "Uçuş boyunca əlaqədə qalın.",
"Airport Transfer": "Hava limanı transferi", "Private transfer at your destination.": "Təyinatda şəxsi transfer.",
"Travel Insurance": "Səyahət sığortası", "Protection for unexpected changes.": "Gözlənilməz dəyişikliklərdən qorunma.",
"Payment": "Ödəniş", "Complete your booking securely.": "Bronunuzu təhlükəsiz tamamlayın.",
"Card Details": "Kart məlumatları", "Name on Card": "Kart üzərindəki ad", "Card Number": "Kart nömrəsi",
"Expiry": "Bitmə tarixi", "CVV": "CVV", "Promo Code": "Promo kod",
"Enter promo code": "Promo kodu daxil edin", "Payment Summary": "Ödəniş xülasəsi",
"Base fare": "Baza qiymət", "Seats": "Oturacaqlar", "Meals": "Yeməklər", "Extras": "Əlavələr",
"Discount": "Endirim", "Taxes & fees": "Vergilər və rüsumlar", "Pay {amount}": "{amount} ödə",
"Continue with Apple Pay to complete your payment securely.": "Ödənişi təhlükəsiz tamamlamaq üçün Apple Pay ilə davam edin.",
"Continue with Google Pay to complete your payment securely.": "Ödənişi təhlükəsiz tamamlamaq üçün Google Pay ilə davam edin.",
"Invalid promo code": "Yanlış promo kod", "{code} applied − {percent}% off": "{code} tətbiq olundu − {percent}% endirim",
"Booking information could not be found. Please complete passenger details first.": "Bron məlumatı tapılmadı. Əvvəlcə sərnişin məlumatlarını tamamlayın.",
"Unable to save payment status. Please try again.": "Ödəniş statusu yadda saxlanılmadı. Yenidən cəhd edin.",
"Please complete all card fields.": "Bütün kart sahələrini doldurun.",
"Please enter a valid card number.": "Düzgün kart nömrəsi daxil edin.",
"Booking Confirmed": "Bron təsdiqləndi",
"Your journey is reserved. A confirmation has been prepared for your records.": "Səyahətiniz rezervasiya olundu. Təsdiq sənədi hazırdır.",
"Booking Reference": "Bron kodu", "Flight Summary": "Uçuş xülasəsi", "Total Paid": "Ödənilən məbləğ",
"Download Confirmation": "Təsdiqi yüklə", "Booking Details": "Bron detalları",
"View and manage your upcoming and past journeys.": "Gələcək və keçmiş səyahətlərinizə baxın və idarə edin.",
"Upcoming": "Gələcək", "Past": "Keçmiş", "Cancelled": "Ləğv edilib",
"No trips yet": "Hələ səyahət yoxdur",
"When you complete a booking, it will appear here.": "Bron tamamladıqda burada görünəcək.",
"Book a Flight": "Uçuş bron et", "Manage": "İdarə et", "Confirmed": "Təsdiqlənib",
"Completed": "Tamamlanıb",
"Find your reservation with your booking reference and last name.": "Bron kodu və soyadınızla rezervasiyanızı tapın.",
"Booking Reference (PNR)": "Bron kodu (PNR)", "Find Booking": "Bronu tap",
"No booking found. Check your reference and last name.": "Bron tapılmadı. Kodu və soyadı yoxlayın.",
"Booking Found": "Bron tapıldı", "Change Booking": "Bronu dəyiş",
"Update your flight date, cabin, or seats.": "Uçuş tarixini, salonu və ya oturacaqları yeniləyin.",
"New flight date": "Yeni uçuş tarixi", "Cabin class": "Salon sinfi", "Seat numbers": "Oturacaq nömrələri",
"Enter seats separated by commas": "Oturacaqları vergüllə ayırın", "Change estimate": "Dəyişiklik smetası",
"Confirm Changes": "Dəyişiklikləri təsdiqlə", "Cancel Booking": "Bronu ləğv et",
"Keep Booking": "Bronu saxla",
"Are you sure you want to cancel this booking?": "Bu bronu ləğv etmək istədiyinizə əminsiniz?",
"Flight Information": "Uçuş məlumatı", "Selected Extras": "Seçilmiş əlavələr",
"No Booking Found": "Bron tapılmadı",
"There is no confirmed booking to display. Complete a booking or search by PNR in Manage Booking.": "Göstəriləcək təsdiqlənmiş bron yoxdur. Bron tamamlayın və ya PNR ilə axtarın.",
"Booking updated successfully.": "Bron uğurla yeniləndi.",
"Booking {pnr} has been cancelled.": "{pnr} bronu ləğv edildi.",
"This booking is already cancelled.": "Bu bron artıq ləğv edilib.",
"Cancelled bookings cannot be changed.": "Ləğv edilmiş bron dəyişdirilə bilməz.",
"Please choose a new flight date.": "Yeni uçuş tarixi seçin.",
"Please enter seat selections for your passengers.": "Sərnişinlər üçün oturacaq daxil edin.",
"Enter exactly {count} seat(s).": "Dəqiq {count} oturacaq daxil edin.",
"Unable to save booking changes. Please try again.": "Dəyişikliklər yadda saxlanılmadı. Yenidən cəhd edin.",
"Unable to cancel this booking. Please try again.": "Bron ləğv edilə bilmədi. Yenidən cəhd edin.",
"Welcome Back": "Xoş gəldiniz", "Sign in to AEROVA": "AEROVA-ya daxil olun",
"Access your trips, profile, and travel preferences.": "Səyahətlərinizə, profilinizə və üstünlüklərinizə çatın.",
"Join AEROVA": "AEROVA-ya qoşulun", "Create your account": "Hesab yaradın",
"Save trips, manage bookings, and personalize your journey.": "Səyahətləri yadda saxlayın, bronları idarə edin və səyahətinizi fərdiləşdirin.",
"Password": "Şifrə", "Confirm Password": "Şifrəni təsdiqləyin", "Create Account": "Hesab yarat",
"Don't have an account?": "Hesabınız yoxdur?", "Already have an account?": "Artıq hesabınız var?",
"Register": "Qeydiyyat", "Back to Home": "Ana səhifəyə qayıt", "you@email.com": "siz@email.com",
"Your password": "Şifrəniz", "Email is required": "E-poçt mütləqdir",
"Password is required": "Şifrə mütləqdir",
"Password must be at least 6 characters": "Şifrə ən azı 6 simvol olmalıdır",
"First name is required": "Ad mütləqdir", "Last name is required": "Soyad mütləqdir",
"Please confirm your password": "Şifrəni təsdiqləyin", "Passwords do not match": "Şifrələr uyğun gəlmir",
"Incorrect email or password": "E-poçt və ya şifrə yanlışdır",
"An account with this email already exists": "Bu e-poçt ilə hesab artıq mövcuddur",
"Account created. You can now sign in.": "Hesab yaradıldı. İndi daxil ola bilərsiniz.",
"My Profile": "Profilim",
"Manage your personal details and saved passengers.": "Şəxsi məlumatlarınızı və yadda saxlanmış sərnişinləri idarə edin.",
"Personal Information": "Şəxsi məlumat", "Save Changes": "Dəyişiklikləri yadda saxla",
"Saved Passengers": "Yadda saxlanmış sərnişinlər", "Add Passenger": "Sərnişin əlavə et",
"Edit Passenger": "Sərnişini redaktə et",
"No saved passengers yet. Add one to speed up future bookings.": "Hələ yadda saxlanmış sərnişin yoxdur. Gələcək bronları sürətləndirmək üçün əlavə edin.",
"Your profile changes have been saved.": "Profil dəyişiklikləri yadda saxlanıldı.",
"Unable to save your profile right now.": "Profil indi yadda saxlanıla bilmədi.",
"Please complete the highlighted fields.": "İşarələnmiş sahələri tamamlayın.",
"Saved passenger profile updated.": "Sərnişin profili yeniləndi.",
"Passenger removed from your saved profiles.": "Sərnişin yadda saxlanmış siyahıdan silindi.",
"Stay updated on bookings, schedule changes, and offers.": "Bronlar, cədvəl dəyişiklikləri və təkliflər haqqında xəbərdar olun.",
"You're all caught up": "Hamısı oxunub",
"You are all caught up. Booking and flight updates will appear here when available.": "Hamısı oxunub. Bron və uçuş yenilikləri burada görünəcək.",
"Mark as read": "Oxunmuş kimi işarələ", "Mark all as read": "Hamısını oxunmuş et",
"Booking Cancelled": "Bron ləğv edildi", "Upcoming Flight Reminder": "Yaxınlaşan uçuş xatırlatması",
"Exclusive Offer": "Xüsusi təklif",
"Cities and shores chosen for atmosphere, culture, and the journey between them.": "Atmosfer, mədəniyyət və aradakı yol üçün seçilmiş şəhərlər və sahillər.",
"Explore the Collection": "Kolleksiyanı kəşf edin",
"Six signature destinations, each with its own atmosphere and an AEROVA fare to begin the journey.": "Hər birinin öz atmosferi və AEROVA tarifı olan altı imza istiqamət.",
"Ready to fly?": "Uçmağa hazırsınız?",
"Search AEROVA flights to your next destination.": "Növbəti istiqamətinizə AEROVA uçuşlarını axtarın.",
"Book Your Journey": "Səyahətinizi bron edin", "Highlights": "Əsas məqamlar",
"Best Time to Visit": "Ən yaxşı ziyarət vaxtı", "The Experience": "Təcrübə",
"Fares shown are starting prices and may vary by date and cabin.": "Göstərilən tariflər başlanğıc qiymətlərdir və tarixə və salona görə dəyişə bilər.",
"The AEROVA Experience": "AEROVA Təcrübəsi",
"Cabins, cuisine, and care designed to make every hour onboard feel intentional.": "Salon, mətbəx və qayğı — hər saatın mənalı keçməsi üçün.",
"Cabin Experiences": "Salon təcrübələri", "Choose the rhythm of your journey.": "Səyahətinizin ritmini seçin.",
"Economy Experience": "Ekonom təcrübəsi",
"Ergonomic seating, thoughtful lighting, and essentials arranged so every journey feels composed from the first moment onboard.": "Erqonomik oturacaqlar, düşünülmüş işıqlandırma və rahat başlanğıc üçün əsaslar.",
"Comfort Experience": "Komfort təcrübəsi",
"Extra room to settle in, preferred seating options, and a calmer cabin rhythm for travelers who value space and ease.": "Daha çox yer, üstün oturacaq seçimləri və sakit salon ritmi.",
"Business Class Experience": "Biznes sinif təcrübəsi",
"Private repose, lie-flat comfort, and attentive service that turns long-haul hours into a quiet continuation of your day.": "Şəxsi rahatlıq, uzanan oturacaq və diqqətli xidmət.",
"Onboard Lifestyle": "Bort həyat tərzi", "Details that shape how you spend the journey.": "Səyahətinizi formalaşdıran detallar.",
"Dining": "Yeməklər",
"Seasonal menus and cabin-specific service, from light plates in Economy to multi-course dining in Business Class.": "Mövsümi menyular və salon üzrə xidmət.",
"Entertainment": "Əyləncə",
"A curated library of films, music, and quiet reading modes — available when you want them, invisible when you do not.": "Filmlər, musiqi və sakit oxu rejimləri.",
"Airport Lounge": "Hava limanı zalı",
"Calm seating, refined refreshments, and a seamless prelude to boarding for eligible Comfort and Business travelers.": "Sakit oturacaqlar və zərif ikramlar.",
"Premium Services": "Premium xidmətlər",
"Priority boarding, Fast Track, and tailored extras that keep your journey moving with quiet efficiency.": "Prioritet miniş, Fast Track və fərdi əlavələr.",
"Fly the AEROVA way": "AEROVA tərzində uçun",
"Reserve your seat and experience travel composed around you.": "Yerinizi bron edin və sizin ətrafınızda qurulmuş səyahəti hiss edin.",
"About AEROVA": "AEROVA haqqında",
"An airline built on composure, clarity, and the belief that every journey should feel considered.": "Sakitlik, aydınlıq və hər səyahətin düşünülmüş olması ideyası üzərində qurulmuş aviaşirkət.",
"Our Story": "Hekayəmiz",
"Today, travelers choose AEROVA for journeys that are as thoughtfully prepared as the destinations they seek.": "Bu gün səyahətçilər AEROVA-nı istiqamətləri qədər düşünülmüş yollar üçün seçir.",
"Mission": "Missiya",
"To elevate every journey with calm service, refined comfort, and effortless clarity.": "Hər səyahəti sakit xidmət, zərif rahatlıq və asan aydınlıqla yüksəltmək.",
"Vision": "Vizyon",
"To become the airline travelers trust when comfort, clarity, and connection matter most.": "Rahatlıq, aydınlıq və bağlantı önəmli olanda etibar edilən aviaşirkət olmaq.",
"Values": "Dəyərlər", "Why Travelers Choose AEROVA": "Səyahətçilər niyə AEROVA seçir",
"Effortless Booking": "Asan bron", "A clear path from search to seat, without noise.": "Axtarışdan oturacağa qədər aydın yol.",
"Considered Comfort": "Düşünülmüş rahatlıq",
"Cabins and service designed around how people actually travel.": "İnsanların real səyahətinə uyğun salon və xidmət.",
"Connected Destinations": "Bağlı istiqamətlər",
"Routes chosen for meaning, not volume alone.": "Yalnız həcm üçün deyil, məna üçün seçilmiş marşrutlar.",
"A Premium Standard": "Premium standart",
"From lounge to landing, every detail is composed to feel intentional.": "Zaldan enişə qədər hər detal düşünülmüşdür.",
"Admin": "Admin", "AEROVA Operations Control": "AEROVA Əməliyyat İdarəsi",
"Dashboard": "Panel", "Airline operations overview": "Aviaşirkət əməliyyatlarına baxış",
"Manage flight operations and status": "Uçuş əməliyyatlarını və statusu idarə et",
"Routes": "Marşrutlar", "Network route management": "Şəbəkə marşrutlarının idarəsi",
"Schedules": "Cədvəllər", "Departure planning and timetable control": "Gediş planlaşdırması və cədvəl nəzarəti",
"Fleet configuration and seat capacity": "Park konfiqurasiyası və oturacaq tutumu",
"Seat Inventory": "Oturacaq ehtiyatı", "Cabin availability by flight": "Uçuş üzrə salon mövcudluğu",
"Bookings": "Bronlar", "Reservation management and cancellations": "Rezervasiya idarəsi və ləğvlər",
"Traveler records and contact details": "Sərnişin qeydləri və əlaqə",
"Total Flights": "Ümumi uçuşlar", "Active Routes": "Aktiv marşrutlar",
"Total Bookings": "Ümumi bronlar", "Available Seats": "Mövcud oturacaqlar",
"Recent Bookings": "Son bronlar", "Upcoming Flights": "Yaxınlaşan uçuşlar",
"PNR": "PNR", "Route": "Marşrut", "All statuses": "Bütün statuslar",
"Search flight, origin, destination": "Uçuş, haradan, haraya axtar",
"Booking {pnr} cancelled.": "{pnr} bronu ləğv edildi.", "Actions": "Əməliyyatlar",
}

RU = {
"Booking": "Бронирование", "Destinations": "Направления", "Experience": "Впечатления", "About": "О нас",
"My Trips": "Мои поездки", "Login": "Вход", "Logout": "Выход", "Notifications": "Уведомления",
"Profile": "Профиль", "Open menu": "Открыть меню", "Close menu": "Закрыть меню", "Search": "Поиск",
"Primary": "Основная", "AEROVA Home": "AEROVA Главная",
"Fly beyond expectations.": "Летите выше ожиданий.", "Quick Links": "Быстрые ссылки",
"Home": "Главная", "Flights": "Рейсы", "Support": "Поддержка", "Help Center": "Справочный центр",
"Contact Us": "Связаться с нами", "Travel Information": "Информация о поездке", "FAQs": "Частые вопросы",
"Follow Us": "Мы в соцсетях", "© 2026 AEROVA. All rights reserved.": "© 2026 AEROVA. Все права защищены.",
"Privacy Policy": "Политика конфиденциальности", "Terms & Conditions": "Условия использования",
"Manage Booking": "Управление бронированием",
"Continue": "Продолжить", "Back": "Назад", "Next": "Далее", "Cancel": "Отмена", "Save": "Сохранить",
"Clear": "Очистить", "Close": "Закрыть", "From": "Откуда", "To": "Куда", "Departure": "Вылет",
"Return": "Возврат", "Passengers": "Пассажиры", "Passenger": "Пассажир", "Cabin Class": "Класс салона",
"Economy": "Эконом", "Comfort": "Комфорт", "Business": "Бизнес", "Non-stop": "Без пересадок",
"1 Stop": "1 пересадка", "Price": "Цена", "Duration": "Длительность", "Stops": "Пересадки",
"Date": "Дата", "Flight": "Рейс", "Status": "Статус", "Total": "Итого", "Details": "Подробнее",
"Select": "Выбрать", "Selected": "Выбрано", "Available": "Доступно", "Unavailable": "Недоступно",
"Required": "Обязательно", "Optional": "Необязательно", "Adult": "Взрослый", "Child": "Ребёнок",
"Infant": "Младенец", "Yes": "Да", "No": "Нет", "Loading…": "Загрузка…", "Edit": "Изменить",
"Remove": "Удалить", "Add": "Добавить", "Apply": "Применить", "Confirm": "Подтвердить",
"Download": "Скачать", "View": "Смотреть", "None": "Нет", "None selected": "Ничего не выбрано",
"per passenger": "на пассажира", "Included": "Включено", "Free": "Бесплатно", "Language": "Язык",
}

# Extend RU with remaining strings by reading AZ keys from AZ map and providing RU for same EN keys
# For brevity, fill RU for all AZ keys using a second pass file if missing keep EN

# Load additional RU translations for keys present in AZ
RU_EXTRA = {
"Luxury Travel Experience": "Роскошные путешествия", "Your Journey": "Ваше путешествие",
"Starts Here": "начинается здесь",
"Discover new destinations, create unforgettable memories and fly beyond expectations.": "Открывайте новые направления, создавайте незабываемые воспоминания и летите выше ожиданий.",
"Book Now": "Забронировать", "Where Would You Like To Fly?": "Куда вы хотите полететь?",
"Try: Baku to Dubai next Friday, 2 passengers, business": "Например: Баку — Дубай в следующую пятницу, 2 пассажира, бизнес",
"Search Flights": "Найти рейсы", "Speak or type your trip in one sentence.": "Скажите или напишите поездку одним предложением.",
"Featured Destinations": "Избранные направления", "Where Will You Go Next?": "Куда отправитесь дальше?",
"Explore unforgettable destinations with AEROVA.": "Откройте незабываемые направления с AEROVA.",
"Explore": "Смотреть", "Why AEROVA": "Почему AEROVA", "Travel, Elevated": "Путешествия на новом уровне",
"Every detail designed for calm, clarity, and comfort.": "Каждая деталь создана для спокойствия, ясности и комфорта.",
"Refined Comfort": "Изысканный комфорт", "Thoughtfully designed cabins for every journey.": "Продуманные салоны для любого путешествия.",
"Signature Destinations": "Знаковые направления",
"Curated routes connecting the world's most compelling cities.": "Маршруты, соединяющие самые вдохновляющие города мира.",
"Premium Experience": "Премиальный опыт",
"Discover a refined travel experience designed around you.": "Откройте изысканное путешествие, созданное вокруг вас.",
"The Aerova Experience": "Опыт Aerova", "Travel in a Class of Your Own": "Путешествуйте в своём классе",
"From refined comfort to elevated service, discover the way you want to travel with AEROVA.": "От изысканного комфорта до высокого сервиса — откройте свой стиль полёта с AEROVA.",
"Economy Class": "Эконом класс",
"Thoughtful comfort, entertainment and everything you need for a smooth journey.": "Продуманный комфорт, развлечения и всё необходимое для спокойного полёта.",
"Explore Economy": "Смотреть Эконом",
"Extra space, thoughtful amenities and a more relaxed way to travel.": "Больше пространства, продуманные удобства и более спокойный полёт.",
"Discover Comfort": "Открыть Комфорт", "Business Class": "Бизнес класс",
"Enjoy spacious seating, refined dining and a more comfortable journey.": "Просторные кресла, изысканная кухня и более комфортное путешествие.",
"Explore Business": "Смотреть Бизнес", "Stay Connected": "Оставайтесь на связи",
"Travel Inspiration, Delivered": "Вдохновение для путешествий",
"Subscribe to receive AEROVA travel updates, destination inspiration and exclusive offers.": "Подпишитесь на обновления AEROVA, идеи направлений и эксклюзивные предложения.",
"Email address": "Адрес эл. почты", "Enter your email address": "Введите адрес эл. почты",
"Subscribe": "Подписаться", "Thank you for subscribing.": "Спасибо за подписку.",
"Please enter a valid email address.": "Введите корректный адрес эл. почты.",
"Aircraft in flight above the clouds": "Самолёт в полёте над облаками",
"Book Your Flight": "Забронируйте рейс", "Find Your AEROVA Flight": "Найдите рейс AEROVA",
"Search, compare and book your perfect journey.": "Ищите, сравнивайте и бронируйте идеальное путешествие.",
"Round Trip": "Туда и обратно", "One Way": "В одну сторону", "Multi City": "Сложный маршрут",
"City or airport": "Город или аэропорт", "Departure Date": "Дата вылета", "Return Date": "Дата возврата",
"Trip type": "Тип поездки", "Flight {n}": "Рейс {n}", "Add Flight": "Добавить рейс",
"Adults": "Взрослые", "Children": "Дети", "Infants": "Младенцы", "Your Search": "Ваш поиск",
"Select Dates": "Выберите даты", "Select departure date": "Выберите дату вылета",
"Select return date": "Выберите дату возврата", "Modify search": "Изменить поиск",
"Voice input for departure": "Голосовой ввод пункта вылета",
"Voice input for destination": "Голосовой ввод пункта назначения",
"Swap departure and destination": "Поменять местами", "Flight booking": "Бронирование рейса",
"Please enter a departure city.": "Укажите город вылета.", "Please enter a destination.": "Укажите город назначения.",
"Departure and destination must be different.": "Пункты вылета и назначения должны отличаться.",
"Please select a departure date.": "Выберите дату вылета.", "Please select a return date.": "Выберите дату возврата.",
"Return date must be after departure.": "Дата возврата должна быть позже вылета.",
"Please select at least one passenger.": "Выберите хотя бы одного пассажира.",
"Available Flights": "Доступные рейсы",
"Available flights in the next 30 days": "Доступные рейсы на ближайшие 30 дней",
"← Modify search": "← Изменить поиск", "Filters & Sort": "Фильтры и сортировка",
"Clear Filters": "Сбросить фильтры", "Sort By": "Сортировать", "Recommended": "Рекомендуемые",
"Cheapest": "Самые дешёвые", "Fastest": "Самые быстрые", "Earliest Departure": "Самый ранний вылет",
"Lowest to Highest": "По возрастанию", "Highest to Lowest": "По убыванию",
"Shortest": "Самые короткие", "Longest": "Самые длинные", "1 flight found": "Найден 1 рейс",
"{count} flights found": "Найдено рейсов: {count}",
"0 flights match your filters": "Нет рейсов по выбранным фильтрам", "Select Flight": "Выбрать рейс",
"View Details": "Подробнее", "Departs": "Вылет", "Arrives": "Прилёт",
"Flight filters and sorting": "Фильтры и сортировка рейсов", "Flight options": "Варианты рейсов",
"No flights found": "Рейсы не найдены",
"Try adjusting your filters or modifying your search.": "Измените фильтры или параметры поиска.",
"Flight Details": "Детали рейса", "Flight Overview": "Обзор рейса", "Schedule": "Расписание",
"Aircraft": "Самолёт", "Cabin Options": "Варианты салона",
"Continue to Seat Selection": "Перейти к выбору мест", "Back to Results": "К результатам",
"Amenities": "Удобства", "Baggage": "Багаж", "From {price}": "От {price}",
"Select Your Seats": "Выберите места", "Choose seats for each passenger.": "Выберите место для каждого пассажира.",
"Occupied": "Занято", "Extra legroom": "Доп. место для ног", "Selection Summary": "Итог выбора",
"Selected seats": "Выбранные места", "No seat selected": "Место не выбрано",
"Select a seat for {name}": "Выберите место для {name}", "Passenger {n}": "Пассажир {n}",
"Please select a seat for every passenger.": "Выберите место для каждого пассажира.",
"This seat is unavailable.": "Это место недоступно.", "Seat map": "Схема мест",
"Passenger Details": "Данные пассажиров",
"Enter traveler information exactly as it appears on travel documents.": "Введите данные точно как в проездных документах.",
"Booking Contact": "Контакт для бронирования", "Email": "Эл. почта", "Phone": "Телефон",
"First Name": "Имя", "Last Name": "Фамилия", "Title": "Обращение", "Date of Birth": "Дата рождения",
"Nationality": "Гражданство", "Passport Number": "Номер паспорта", "Passport Expiry": "Срок действия паспорта",
"Booking Summary": "Сводка бронирования", "Continue to Payment": "Перейти к оплате",
"Save passenger": "Сохранить пассажира", "This field is required": "Обязательное поле",
"Enter a valid email address": "Введите корректный email", "Enter a valid phone number": "Введите корректный телефон",
"Baggage Selection": "Выбор багажа", "Add checked baggage for your journey.": "Добавьте регистрируемый багаж к поездке.",
"Cabin bag included": "Ручная кладь включена", "Continue without extra baggage": "Продолжить без доп. багажа",
"Baggage total": "Итого за багаж", "Baggage for {name}": "Багаж для {name}",
"No extra baggage": "Без доп. багажа", "23 kg checked bag": "Багаж 23 кг",
"32 kg checked bag": "Багаж 32 кг", "2 × 23 kg checked bags": "2 × 23 кг багажа",
"Meal Selection": "Выбор питания", "Choose meals for your flight.": "Выберите питание на рейс.",
"Continue without meals": "Продолжить без питания", "Meals total": "Итого за питание",
"Standard meal": "Стандартное питание", "Vegetarian": "Вегетарианское", "Vegan": "Веганское",
"Halal": "Халяль", "Children's meal": "Детское питание", "No meal selected": "Питание не выбрано",
"Meal for {name}": "Питание для {name}", "Extra Services": "Доп. услуги",
"Enhance your journey with optional extras.": "Дополните путешествие необязательными услугами.",
"Continue without extras": "Продолжить без доп. услуг", "Extras total": "Итого за услуги",
"Airport Lounge Access": "Доступ в зал ожидания",
"Relax before departure in a premium lounge.": "Отдохните перед вылетом в премиальном зале.",
"Priority Boarding": "Приоритетная посадка", "Board early and settle in with ease.": "Садитесь раньше и устраивайтесь спокойно.",
"Inflight Wi‑Fi": "Wi‑Fi на борту", "Stay connected throughout your flight.": "Оставайтесь на связи во время полёта.",
"Airport Transfer": "Трансфер из аэропорта", "Private transfer at your destination.": "Частный трансфер в пункте назначения.",
"Travel Insurance": "Страхование", "Protection for unexpected changes.": "Защита при неожиданных изменениях.",
"Payment": "Оплата", "Complete your booking securely.": "Завершите бронирование безопасно.",
"Card Details": "Данные карты", "Name on Card": "Имя на карте", "Card Number": "Номер карты",
"Expiry": "Срок", "Promo Code": "Промокод", "Enter promo code": "Введите промокод",
"Payment Summary": "Сводка оплаты", "Base fare": "Базовый тариф", "Seats": "Места",
"Meals": "Питание", "Extras": "Услуги", "Discount": "Скидка", "Taxes & fees": "Налоги и сборы",
"Pay {amount}": "Оплатить {amount}",
"Continue with Apple Pay to complete your payment securely.": "Продолжите с Apple Pay для безопасной оплаты.",
"Continue with Google Pay to complete your payment securely.": "Продолжите с Google Pay для безопасной оплаты.",
"Invalid promo code": "Неверный промокод", "{code} applied − {percent}% off": "{code} применён − скидка {percent}%",
"Booking information could not be found. Please complete passenger details first.": "Данные бронирования не найдены. Сначала заполните данные пассажиров.",
"Unable to save payment status. Please try again.": "Не удалось сохранить статус оплаты. Попробуйте снова.",
"Please complete all card fields.": "Заполните все поля карты.",
"Please enter a valid card number.": "Введите корректный номер карты.",
"Booking Confirmed": "Бронирование подтверждено",
"Your journey is reserved. A confirmation has been prepared for your records.": "Ваше путешествие зарезервировано. Подтверждение готово.",
"Booking Reference": "Код бронирования", "Flight Summary": "Сводка рейса", "Total Paid": "Оплачено",
"Download Confirmation": "Скачать подтверждение", "Booking Details": "Детали бронирования",
"View and manage your upcoming and past journeys.": "Просматривайте и управляйте предстоящими и прошедшими поездками.",
"Upcoming": "Предстоящие", "Past": "Прошедшие", "Cancelled": "Отменённые",
"No trips yet": "Пока нет поездок",
"When you complete a booking, it will appear here.": "После завершения бронирования оно появится здесь.",
"Book a Flight": "Забронировать рейс", "Manage": "Управлять", "Confirmed": "Подтверждено",
"Completed": "Завершено",
"Find your reservation with your booking reference and last name.": "Найдите бронирование по коду и фамилии.",
"Booking Reference (PNR)": "Код бронирования (PNR)", "Find Booking": "Найти бронирование",
"No booking found. Check your reference and last name.": "Бронирование не найдено. Проверьте код и фамилию.",
"Booking Found": "Бронирование найдено", "Change Booking": "Изменить бронирование",
"Update your flight date, cabin, or seats.": "Обновите дату рейса, класс салона или места.",
"New flight date": "Новая дата рейса", "Cabin class": "Класс салона", "Seat numbers": "Номера мест",
"Enter seats separated by commas": "Укажите места через запятую", "Change estimate": "Оценка изменения",
"Confirm Changes": "Подтвердить изменения", "Cancel Booking": "Отменить бронирование",
"Keep Booking": "Оставить бронирование",
"Are you sure you want to cancel this booking?": "Вы уверены, что хотите отменить это бронирование?",
"Flight Information": "Информация о рейсе", "Selected Extras": "Выбранные услуги",
"No Booking Found": "Бронирование не найдено",
"There is no confirmed booking to display. Complete a booking or search by PNR in Manage Booking.": "Нет подтверждённого бронирования для отображения. Завершите бронирование или найдите по PNR.",
"Booking updated successfully.": "Бронирование успешно обновлено.",
"Booking {pnr} has been cancelled.": "Бронирование {pnr} отменено.",
"This booking is already cancelled.": "Это бронирование уже отменено.",
"Cancelled bookings cannot be changed.": "Отменённые бронирования нельзя изменить.",
"Please choose a new flight date.": "Выберите новую дату рейса.",
"Please enter seat selections for your passengers.": "Укажите места для пассажиров.",
"Enter exactly {count} seat(s).": "Введите ровно {count} мест(а).",
"Unable to save booking changes. Please try again.": "Не удалось сохранить изменения. Попробуйте снова.",
"Unable to cancel this booking. Please try again.": "Не удалось отменить бронирование. Попробуйте снова.",
"Welcome Back": "С возвращением", "Sign in to AEROVA": "Войдите в AEROVA",
"Access your trips, profile, and travel preferences.": "Доступ к поездкам, профилю и настройкам.",
"Join AEROVA": "Присоединяйтесь к AEROVA", "Create your account": "Создайте аккаунт",
"Save trips, manage bookings, and personalize your journey.": "Сохраняйте поездки, управляйте бронированиями и персонализируйте путешествие.",
"Password": "Пароль", "Confirm Password": "Подтвердите пароль", "Create Account": "Создать аккаунт",
"Don't have an account?": "Нет аккаунта?", "Already have an account?": "Уже есть аккаунт?",
"Register": "Регистрация", "Back to Home": "На главную", "Your password": "Ваш пароль",
"Email is required": "Укажите эл. почту", "Password is required": "Укажите пароль",
"Password must be at least 6 characters": "Пароль должен быть не короче 6 символов",
"First name is required": "Укажите имя", "Last name is required": "Укажите фамилию",
"Please confirm your password": "Подтвердите пароль", "Passwords do not match": "Пароли не совпадают",
"Incorrect email or password": "Неверный email или пароль",
"An account with this email already exists": "Аккаунт с таким email уже существует",
"Account created. You can now sign in.": "Аккаунт создан. Теперь можно войти.",
"My Profile": "Мой профиль",
"Manage your personal details and saved passengers.": "Управляйте личными данными и сохранёнными пассажирами.",
"Personal Information": "Личная информация", "Save Changes": "Сохранить изменения",
"Saved Passengers": "Сохранённые пассажиры", "Add Passenger": "Добавить пассажира",
"Edit Passenger": "Изменить пассажира",
"No saved passengers yet. Add one to speed up future bookings.": "Пока нет сохранённых пассажиров. Добавьте, чтобы ускорить будущие бронирования.",
"Your profile changes have been saved.": "Изменения профиля сохранены.",
"Unable to save your profile right now.": "Не удалось сохранить профиль.",
"Please complete the highlighted fields.": "Заполните выделенные поля.",
"Saved passenger profile updated.": "Профиль пассажира обновлён.",
"Passenger removed from your saved profiles.": "Пассажир удалён из сохранённых.",
"Stay updated on bookings, schedule changes, and offers.": "Будьте в курсе бронирований, изменений расписания и предложений.",
"You're all caught up": "Вы всё прочитали",
"You are all caught up. Booking and flight updates will appear here when available.": "Вы всё прочитали. Обновления о бронированиях и рейсах появятся здесь.",
"Mark as read": "Отметить прочитанным", "Mark all as read": "Отметить все",
"Booking Cancelled": "Бронирование отменено", "Upcoming Flight Reminder": "Напоминание о рейсе",
"Exclusive Offer": "Эксклюзивное предложение",
"Cities and shores chosen for atmosphere, culture, and the journey between them.": "Города и побережья, выбранные за атмосферу, культуру и путь между ними.",
"Explore the Collection": "Коллекция направлений",
"Six signature destinations, each with its own atmosphere and an AEROVA fare to begin the journey.": "Шесть знаковых направлений — у каждого своя атмосфера и тариф AEROVA.",
"Ready to fly?": "Готовы лететь?",
"Search AEROVA flights to your next destination.": "Найдите рейсы AEROVA в ваш следующий город.",
"Book Your Journey": "Забронируйте путешествие", "Highlights": "Основные моменты",
"Best Time to Visit": "Лучшее время для поездки", "The Experience": "Впечатления",
"Fares shown are starting prices and may vary by date and cabin.": "Указаны стартовые тарифы; цена зависит от даты и класса салона.",
"The AEROVA Experience": "Опыт AEROVA",
"Cabins, cuisine, and care designed to make every hour onboard feel intentional.": "Салоны, кухня и забота, благодаря которым каждый час на борту имеет значение.",
"Cabin Experiences": "Салонные впечатления", "Choose the rhythm of your journey.": "Выберите ритм вашего путешествия.",
"Economy Experience": "Эконом",
"Ergonomic seating, thoughtful lighting, and essentials arranged so every journey feels composed from the first moment onboard.": "Эргономичные кресла, продуманный свет и всё необходимое с первых минут на борту.",
"Comfort Experience": "Комфорт",
"Extra room to settle in, preferred seating options, and a calmer cabin rhythm for travelers who value space and ease.": "Больше пространства, предпочтительные места и более спокойный ритм салона.",
"Business Class Experience": "Бизнес класс",
"Private repose, lie-flat comfort, and attentive service that turns long-haul hours into a quiet continuation of your day.": "Личное пространство, кресла-кровати и внимательный сервис в долгом полёте.",
"Onboard Lifestyle": "Образ жизни на борту", "Details that shape how you spend the journey.": "Детали, которые формируют ваше путешествие.",
"Dining": "Питание",
"Seasonal menus and cabin-specific service, from light plates in Economy to multi-course dining in Business Class.": "Сезонные меню и сервис по классу салона.",
"Entertainment": "Развлечения",
"A curated library of films, music, and quiet reading modes — available when you want them, invisible when you do not.": "Фильмы, музыка и тихие режимы чтения.",
"Airport Lounge": "Зал ожидания",
"Calm seating, refined refreshments, and a seamless prelude to boarding for eligible Comfort and Business travelers.": "Спокойные места и изысканные угощения перед посадкой.",
"Premium Services": "Премиальные услуги",
"Priority boarding, Fast Track, and tailored extras that keep your journey moving with quiet efficiency.": "Приоритетная посадка, Fast Track и персональные опции.",
"Fly the AEROVA way": "Летите в стиле AEROVA",
"Reserve your seat and experience travel composed around you.": "Забронируйте место и ощутите путешествие, созданное вокруг вас.",
"About AEROVA": "О AEROVA",
"An airline built on composure, clarity, and the belief that every journey should feel considered.": "Авиакомпания, основанная на спокойствии, ясности и идее, что каждое путешествие должно быть продуманным.",
"Our Story": "Наша история",
"Today, travelers choose AEROVA for journeys that are as thoughtfully prepared as the destinations they seek.": "Сегодня путешественники выбирают AEROVA за пути, столь же продуманные, как и сами направления.",
"Mission": "Миссия",
"To elevate every journey with calm service, refined comfort, and effortless clarity.": "Возвышать каждое путешествие спокойным сервисом, изысканным комфортом и ясностью.",
"Vision": "Видение",
"To become the airline travelers trust when comfort, clarity, and connection matter most.": "Стать авиакомпанией, которой доверяют, когда важны комфорт, ясность и связь.",
"Values": "Ценности", "Why Travelers Choose AEROVA": "Почему выбирают AEROVA",
"Effortless Booking": "Простое бронирование", "A clear path from search to seat, without noise.": "Понятный путь от поиска до места без лишнего шума.",
"Considered Comfort": "Продуманный комфорт",
"Cabins and service designed around how people actually travel.": "Салоны и сервис, созданные под реальные поездки.",
"Connected Destinations": "Связанные направления",
"Routes chosen for meaning, not volume alone.": "Маршруты, выбранные ради смысла, а не только объёма.",
"A Premium Standard": "Премиальный стандарт",
"From lounge to landing, every detail is composed to feel intentional.": "От зала до посадки каждая деталь продумана.",
"Admin": "Админ", "AEROVA Operations Control": "AEROVA Центр управления",
"Dashboard": "Панель", "Airline operations overview": "Обзор авиационных операций",
"Manage flight operations and status": "Управление рейсами и статусами",
"Routes": "Маршруты", "Network route management": "Управление маршрутной сетью",
"Schedules": "Расписания", "Departure planning and timetable control": "Планирование вылетов и контроль расписания",
"Fleet configuration and seat capacity": "Конфигурация флота и вместимость",
"Seat Inventory": "Инвентарь мест", "Cabin availability by flight": "Доступность салона по рейсам",
"Bookings": "Бронирования", "Reservation management and cancellations": "Управление и отмена бронирований",
"Traveler records and contact details": "Записи пассажиров и контакты",
"Total Flights": "Всего рейсов", "Active Routes": "Активные маршруты",
"Total Bookings": "Всего бронирований", "Available Seats": "Доступные места",
"Recent Bookings": "Недавние бронирования", "Upcoming Flights": "Ближайшие рейсы",
"Route": "Маршрут", "All statuses": "Все статусы",
"Search flight, origin, destination": "Поиск рейса, вылета, назначения",
"Booking {pnr} cancelled.": "Бронирование {pnr} отменено.", "Actions": "Действия",
}
RU.update(RU_EXTRA)

def translate_tree(node, mapping):
    if isinstance(node, dict):
        return {k: translate_tree(v, mapping) for k, v in node.items()}
    if isinstance(node, str):
        return mapping.get(node, node)
    return node

# Build overlays as full trees (not diffs) matching en structure — build_i18n deep_merges anyway
az_tree = translate_tree(en, AZ)
ru_tree = translate_tree(en, RU)

# Report untranslated
def collect_leaves(node, out):
    if isinstance(node, dict):
        for v in node.values(): collect_leaves(v, out)
    elif isinstance(node, str):
        out.add(node)

leaves = set(); collect_leaves(en, leaves)
missing_az = sorted(s for s in leaves if s not in AZ)
missing_ru = sorted(s for s in leaves if s not in RU)
print("EN leaves", len(leaves))
print("Missing AZ", len(missing_az))
print("Missing RU", len(missing_ru))
if missing_az[:10]:
    print("sample AZ missing:", missing_az[:10])

(ROOT / "az.json").write_text(json.dumps(az_tree, ensure_ascii=False, indent=2), encoding="utf-8")
(ROOT / "ru.json").write_text(json.dumps(ru_tree, ensure_ascii=False, indent=2), encoding="utf-8")
print("Wrote az.json and ru.json")
